MVC/WebApplication3/Controllers/PedidoClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.SqlServer;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    
     
    public class PedidoClienteController : Controller
    {
        private CREntities1 db = new CREntities1();
     //   private List<Models.ProductosJqueryViewModel> _lstproductos = new List<Models.ProductosJqueryViewModel>();
       

        // GET: /PedidoCliente/
        public ActionResult Index()
        {
            var pedidos_clientes = db.PEDIDOS_CLIENTES.Include(p => p.AspNetUsers).Include(p => p.CLIENTES).Include(p => p.ESTADOS_PEDIDOS).Include(x => x.PEDIDOS_CLIENTES_DETALLES);
            List<PedidoClienteDashViewModel> pc = new List<PedidoClienteDashViewModel>();

            foreach (var item in pedidos_clientes)
            {
                PedidoClienteDashViewModel pcd = new PedidoClienteDashViewModel();
                pcd.PedidoID = item.PedidoClienteID;
                pcd.AspNetUsers = item.AspNetUsers;
                pcd.CLIENTES = item.CLIENTES;
                pcd.ESTADOS_PEDIDOS = item.ESTADOS_PEDIDOS;
                pcd.FechaCreacion = item.FechaCreacion;

                
                var totalPrecio = item.PEDIDOS_CLIENTES_DETALLES.Sum(x => x.PrecioUnitario * x.Cantidad);
                pcd.Total = totalPrecio;

                pc.Add(pcd);
            }

            

            return View(pc);
        }


        // GET: /PedidoCliente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PEDIDOS_CLIENTES pedidos_clientes = db.PEDIDOS_CLIENTES.Find(id);
            if (pedidos_clientes == null)
            {
                return HttpNotFound();
            }
            return View(pedidos_clientes);
        }

        // GET: /PedidoCliente/Create
        public ActionResult Create()
        {
            ViewBag.AsignatarioID = new SelectList(db.AspNetUsers, "Id", "Email");
            ViewBag.ClienteID = new SelectList(db.CLIENTES, "ClienteID", "Nombre");
            ViewBag.EPedidoID = new SelectList(db.ESTADOS_PEDIDOS, "EPedidoID", "Nombre");
            return View();
        }

        // POST: /PedidoCliente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="PedidoClienteID,EPedidoID,ClienteID,AsignatarioID,Total")] PEDIDOS_CLIENTES pedidos_clientes)
        {
            if (ModelState.IsValid)
            {
                db.PEDIDOS_CLIENTES.Add(pedidos_clientes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AsignatarioID = new SelectList(db.AspNetUsers, "Id", "Email", pedidos_clientes.AsignatarioID);
            ViewBag.ClienteID = new SelectList(db.CLIENTES, "ClienteID", "Nombre", pedidos_clientes.ClienteID);
            ViewBag.EPedidoID = new SelectList(db.ESTADOS_PEDIDOS, "EPedidoID", "Nombre", pedidos_clientes.EPedidoID);
            return View(pedidos_clientes);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GenerarPedido(FormCollection col)
        {

            var a = Request.Form["hddCliente"];
            var b = Request.Form["hddProductos"];
            var c = Request.Form["hddTotal"];
            var d = Request.Form["hddAsignatario"];
            
            // CONTADO
            var chk1 = Convert.ToBoolean(Request.Form["chk1"].Split(',')[0]);
            // CHEQUE
            var chk2 = Convert.ToBoolean(Request.Form["chk2"].Split(',')[0]);
            // MERCADERIA
            var chk3 = Convert.ToBoolean(Request.Form["chk3"].Split(',')[0]);

            var f = Request.Form["hddTipoFacturacion"].Trim();

                        
            bool MyBoolValue = Convert.ToBoolean(Request.Form["chk1"].Split(',')[0]);

            try
            {
                JavaScriptSerializer js = new JavaScriptSerializer();
                List<Models.ProductosJqueryViewModel> _lstProductos = js.Deserialize<List<Models.ProductosJqueryViewModel>>(b);

                PEDIDOS_CLIENTES pc = new PEDIDOS_CLIENTES();
                pc.AsignatarioID = db.AspNetUsers.Where(x => x.UserName == d).FirstOrDefault().Id;
                pc.ClienteID = Convert.ToInt32(a);
                pc.EPedidoID = db.ESTADOS_PEDIDOS.Where(x => x.Nombre == "CREADO").Select(j => j.EPedidoID).FirstOrDefault();
                pc.Total = Convert.ToDecimal(c);
                pc.FechaCreacion = DateTime.Now;
                pc.FechaModificacion = DateTime.Now;
                pc.TFacturacionID = db.TIPO_FACTURACIONES.Find(Convert.ToInt32(f)).TFacturacionID;
                
                if (chk1){
                
                    TIPO_PAGOS tp = db.TIPO_PAGOS.Find(1);
                    pc.TIPO_PAGOS.Add(tp);
                
                }
                if (chk2)
                {

                    TIPO_PAGOS tp = db.TIPO_PAGOS.Find(2);
                    pc.TIPO_PAGOS.Add(tp);

                }
                if (chk3)
                {

                    TIPO_PAGOS tp = db.TIPO_PAGOS.Find(3);
                    pc.TIPO_PAGOS.Add(tp);

                }

                db.PEDIDOS_CLIENTES.Add(pc);
                db.SaveChanges();

                foreach (var item in _lstProductos)
                {
                    PEDIDOS_CLIENTES_DETALLES pd = new PEDIDOS_CLIENTES_DETALLES();
                    
                    pd.Cantidad = Convert.ToInt32(item.cantidad);
                    PRODUCTOS p = db.PRODUCTOS.Where(x => x.ProductoID == item.productoID).FirstOrDefault();
                    if (p != null)
                    {
                        pd.ProductoID = p.ProductoID;
                        pd.Detalle = p.Detalle;
                        pd.PrecioUnitario = item.precio;
                        pd.PedidoClienteID = pc.PedidoClienteID;
                        db.PEDIDOS_CLIENTES_DETALLES.Add(pd);
                        db.SaveChanges();
                    }
                    else
                        throw new Exception();
                                        
                }


            }
            catch (Exception)
            {
                
                throw;
            }

            if (ModelState.IsValid)
            {
                db.SaveChanges();
                return RedirectToAction("Index");
            }

          
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GuardarCambios(FormCollection col) {

            var a = Request.Form["hddCliente"];
            var b = Request.Form["hddProductos"];
            var c = Request.Form["hddTotal"];
            var d = Request.Form["hddAsignatario"];
            var e = Request.Form["hddPedidoID"];

            try
            {
                JavaScriptSerializer js = new JavaScriptSerializer();
                List<Models.ProductosJqueryViewModel> _lstProductos = js.Deserialize<List<Models.ProductosJqueryViewModel>>(b);

                PEDIDOS_CLIENTES pc = db.PEDIDOS_CLIENTES.Find(Convert.ToInt32(e));
                if (pc == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
 
                pc.AsignatarioID = db.AspNetUsers.Where(x => x.UserName == d).FirstOrDefault().Id;
                pc.ClienteID = Convert.ToInt32(a);
               // pc.EPedidoID = db.ESTADOS_PEDIDOS.Where(x => x.Nombre == "CREADO").Select(j => j.EPedidoID).FirstOrDefault();
                pc.Total = Convert.ToDecimal(c);
                pc.FechaCreacion = DateTime.Now;
                pc.FechaModificacion = DateTime.Now;

                if (ModelState.IsValid)
                {
                    
                       // SubCategory orig = db.SubCategory.Single(x => x.ID == subcategory.id);
                        if (TryUpdateModel<PEDIDOS_CLIENTES>(pc))
                        {
                            db.SaveChanges();
                        }
                    
                    

                }
                IQueryable<PEDIDOS_CLIENTES_DETALLES> pd = db.PEDIDOS_CLIENTES_DETALLES.Where(x => x.PedidoClienteID == pc.PedidoClienteID).Include(x => x.PRODUCTOS);
                
                if (pd == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

                    foreach (var p in _lstProductos)
                    {
                        PEDIDOS_CLIENTES_DETALLES pcd = pd.Single(x => x.ProductoID == p.productoID );

                        if (pcd != null)
                        {
                            pcd.ProductoID = p.productoID;
                            pcd.Cantidad = Convert.ToInt32(p.cantidad);
                            pcd.PrecioUnitario = p.precio;
                            db.SaveChanges();
                            

                        }
                        else
                        {
                            //SI NO LO ENCUENTRA CREA UN NUEVO DETALLE CON EL PRODUCTO
                            if (p != null)
                            {
                                PEDIDOS_CLIENTES_DETALLES _pcd = new PEDIDOS_CLIENTES_DETALLES();
                                _pcd.Cantidad = Convert.ToInt32(p.cantidad);
                                PRODUCTOS producto = db.PRODUCTOS.Where(x => x.ProductoID == p.productoID).FirstOrDefault();
                                if (p != null)

MVC/WebApplication3/Views/PedidoCliente/CrearNuevoPedido.cshtml
@model WebApplication3.Models.ModelViewEditFactura
@{
    ViewBag.Title = "View1";
}

@section Scripts
{

    <script type="text/javascript">

        var productosArray = [];

        function QuitarProducto(id) {

            console.log("Se quitara el producto ID : " + id);

            for (var i = 0; i < productosArray.length; i++) {
                if (productosArray[i].productoID == id) {
                    productosArray.pop(productosArray[i]);
                }
            }

            console.log(JSON.stringify(productosArray));


            $.ajax({
                type: "POST",
                url: '@Url.Action("AgregarProductoGrid")',
                data: JSON.stringify(productosArray),
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // alert("Data has been added successfully.");
                    $('#GridProducto').html(data);
                    //$("#StudentName").removeAttr("placeholder");
                    // $("#buscarCliente").val(data.data);
                    console.log("Respuesta:" + data);
                },
                error: function () {
                    console.log("Error al retornar");
                    // alert("Error while inserting data");
                }
            });
            return false;


        }


        function CalcularTotal() {



            var a = $('.subtotal').not('.grid-header');
            console.log("valor de a :" + a[0].innerText);
            var total = parseFloat(0);

            for (var i = 0; i < a.length; i++) {

                console.log(parseFloat(a[i].innerText.replace("$", "")))
                total += parseFloat(a[i].innerText.replace("$", ""));

            }
            console.log("valor de total: " + total);
            $('#txtTotales').val(total);

        }


        function EnviarFormulario () {



            $('#hddCliente').val($('#hddClienteID').val());
            $('#hddProductos').val(JSON.stringify(productosArray));
            $('#hddTotal').val($('#txtTotales').val());
            $('#hddAsignatario').val($('#Usuarios').val());
           // $('#hddTipoPago').val($('#slTipoPagos').val());
            $('#hddTipoFacturacion').val($('#TipoFacturacion').val());

            console.log($('#hddCliente').val());
            console.log($('#hddAsignatario').val());
            console.log($('#hddProductos').val());
            console.log($('#hddTotal').val());
            console.log($('#hddTipoPago').val());
            console.log($('#hddTipoFacturacion').val());

            $('form')[0].submit();
               
        }


        $(function () {








            $("#btnSearchCliente").click(function () {

                console.log("dentro de function cliente");
                //console.log('{keyword: ' + JSON.stringify($("#buscarCliente").val()) + '}');
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("BuscarNombreCliente")',
                    data: '{keyword: ' + JSON.stringify($("#buscarCliente").val()) + '}',
                    dataType: "html",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        // alert("Data has been added successfully.");

                        //$("#StudentName").removeAttr("placeholder");
                        // $("#buscarCliente").val(data.data);
                        $('#ClienteDetalle').html(data);
                    },
                    error: function () {
                        console.log("Error al retornar");
                        // alert("Error while inserting data");
                    }
                });
                return false;

            });

            $("#btnSearchProducto").click(function () {

                console.log("dentro de function prodcuto");

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("BuscarProducto")',
                    data: '{keyword: ' + JSON.stringify($("#buscarProducto").val()) + '}',
                    dataType: "html",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        // alert("Data has been added successfully.");

                        //$("#StudentName").removeAttr("placeholder");
                        // $("#buscarCliente").val(data.data);
                        $('#ProductoDetalle').html(data);
                    },
                    error: function () {
                        console.log("Error al retornar");
                        // alert("Error while inserting data");
                    }
                });
                return false;

            });


            $("#btnAgregarProducto").click(function () {

                console.log("dentro de function cliente: " + $("#ProductoID").val());


                var flag = 0;

                for (var i = 0; i < productosArray.length; i++) {
                    if( productosArray[i].productoID == $("#ProductoID").val())
                    {
                        productosArray[i].cantidad += parseInt($("#txtCantidad").val());
                        productosArray[i].subtotal = parseFloat(productosArray[i].cantidad * parseFloat($("#txtPrecio").val()));
                        flag = 1;
                    }

                }
                console.log("Antes " + productosArray);

                if (flag == 0) {
                    productosArray.push({
                        productoID: $("#ProductoID").val(),
                        descripcion: $("#txtDescripcion").val(),
                        cantidad: parseInt($("#txtCantidad").val()),
                        precio: parseFloat($("#txtPrecio").val()),
                        subtotal: parseFloat(parseInt($("#txtCantidad").val()) *  parseFloat($("#txtPrecio").val()))
                    });
                }

                console.log("Despues " + productosArray);
                //var product = { productoID: $("#ProductoID").val(), cantidad: $("#txtCantidad").val() };

                // arrayProductos.push(product);

                //var keyword = JSON.stringify(arrayProductos);
                //var dat = JSON.stringify(arrayProductos);

                // console.log(JSON.stringify($("#buscarProducto").val()));
                console.log(JSON.stringify(productosArray));
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("AgregarProductoGrid")',
                    data: JSON.stringify(productosArray),
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        // alert("Data has been added successfully.");
                        $('#GridProducto').html(data);
                        CalcularTotal();
                        //$("#StudentName").removeAttr("placeholder");
                        // $("#buscarCliente").val(data.data);
                        console.log("Respuesta:" + data);
                    },
                    error: function () {
                        console.log("Error al retornar");
                        // alert("Error while inserting data");
                    }
                });
                return false;




            });




        });


    </script>
}

<h2>Nuevo Pedido de Cliente</h2>


<div id="Asignatario">

    
    @Html.Partial("_PartialAsignatarios", Model.usuarios)

    
    

</div>

<br />

<div>

    @Html.Label("Nombre:")
    @Html.TextBox("buscarCliente")

    <button id="btnSearchCliente">Buscar</button>

    <br />
</div>

@using (Html.BeginForm("GenerarPedido", "PedidoCliente", FormMethod.Post))
{

    
    
    @Html.AntiForgeryToken()
    @Html.Hidden("hddCliente");
    @Html.Hidden("hddProductos");
    @Html.Hidden("hddTotal");
    @Html.Hidden("hddAsignatario");
    @Html.Hidden("hddTipoPago");
    @Html.Hidden("hddTipoFacturacion");



   

<div id="ClienteDetalle">

    @Html.Partial("_PartialDetalleCliente", new WebApplication3.Models.CLIENTES())
    
</div>

    @Html.Partial("_PartialFacturacionYPago", Model.fyp)

 
    <br />
    <div>

    @Html.Label("Buscar Producto:")
    @Html.TextBox("buscarProducto")

    <button id="btnSearchProducto">Buscar</button>

    <br />

    </div>
    
     <div id="ProductoDetalle">
        
        @Html.Partial("_PartialDetalleProducto", new WebApplication3.Models.PRODUCTOS())


    </div>
    <br />

       
    <div>

    @Html.Label("Agregar Producto")

    <button id="btnAgregarProducto">Agregar</button>

    <br />

    </div>

    <div id="GridProducto">
        

        @Html.Partial("_PartialGridProductos", new List<WebApplication3.Models.ProductosJqueryViewModel>() )


    </div>

<div >

    <h3>Total : </h3> <input id="txtTotales" disabled="disabled" />

</div>
    <br />

    <button id="btnsave" onclick="EnviarFormulario()" type="button" class="btn btn-default"> Generar </button>
}

@Html.ActionLink("Ir a Inicio", "Index")

MVC/WebApplication3/Views/PedidoCliente/Create.cshtml
@model WebApplication3.Models.PEDIDOS_CLIENTES

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PEDIDOS_CLIENTES</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.EPedidoID, "EPedidoID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EPedidoID", String.Empty)
                @Html.ValidationMessageFor(model => model.EPedidoID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteID, "ClienteID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteID", String.Empty)
                @Html.ValidationMessageFor(model => model.ClienteID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AsignatarioID, "AsignatarioID", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AsignatarioID", String.Empty)
                @Html.ValidationMessageFor(model => model.AsignatarioID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Total, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Total)
                @Html.ValidationMessageFor(model => model.Total)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/WebApplication3/Views/PedidoCliente/Edit.cshtml
@model WebApplication3.Models.PEDIDOS_CLIENTES

@{
    ViewBag.Title = "View1";
}


@section Scripts
{

    <script type="text/javascript">

    var productosArray = [];

    function QuitarProducto(id) {

        console.log("Se quitara el producto ID : " + id);

        for (var i = 0; i < productosArray.length; i++) {
            if (productosArray[i].productoID == id) {
                productosArray.pop(productosArray[i]);
            }
        }

        console.log(JSON.stringify(productosArray));


        $.ajax({
            type: "POST",
            url: '@Url.Action("AgregarProductoGrid")',
            data: JSON.stringify(productosArray),
            contentType: "application/json; charset=utf-8",
            success: function (data) {
                // alert("Data has been added successfully.");
                $('#GridProducto').html(data);
                //$("#StudentName").removeAttr("placeholder");
                // $("#buscarCliente").val(data.data);
                console.log("Respuesta:" + data);
            },
            error: function () {
                console.log("Error al retornar");
                // alert("Error while inserting data");
            }
        });
        return false;


    }

    function LlenarArray(){


        var json = [];

        json = @Html.Raw(Json.Encode(ViewBag.Productos));


        for (var i = 0; i < json.length; i++) {

            //productosArray.push(json[i]);

            productosArray.push({
                productoID: json[i].productoID,
                descripcion: json[i].descripcion,
                cantidad: parseInt(json[i].cantidad),
                precio: parseFloat(json[i].precio),
                subtotal: parseFloat(parseInt(json[i].cantidad) *  parseFloat(json[i].precio))
            });



        }

        console.log(productosArray.length);


    }


    function CalcularTotal() {



        var a = $('.subtotal').not('.grid-header');
        console.log("valor de a :" + a[0].innerText);
        var total = parseFloat(0);

        for (var i = 0; i < a.length; i++) {

            console.log(parseFloat(a[i].innerText.replace("$", "")))
            total += parseFloat(a[i].innerText.replace("$", ""));

        }
        console.log("valor de total: " + total);
        $('#txtTotales').val(total);

    }


    function EnviarFormulario () {



        $('#hddCliente').val($('#hddClienteID').val());
        $('#hddProductos').val(JSON.stringify(productosArray));
        $('#hddTotal').val($('#txtTotales').val());
        $('#hddAsignatario').val($('#AsignatarioID').val());
        $('#hddPedidoID').val(@Html.DisplayFor( x => x.PedidoClienteID ));

        //hddPedidoID

        console.log($('#hddCliente'));
        console.log($('#hddProductos'));
        console.log($('#hddTotal').val());
        console.log($('#hddAsignatario').val());
        console.log($('#hddPedidoID').val());

        $('form')[0].submit();

    }


    $(function () {

        LlenarArray();

        CalcularTotal();




        $("#btnSearchCliente").click(function () {

            console.log("dentro de function cliente");

            $.ajax({
                type: "POST",
                url: '@Url.Action("BuscarNombreCliente")',
                data: '{keyword: ' + JSON.stringify($("#buscarCliente").val()) + '}',
                dataType: "html",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // alert("Data has been added successfully.");

                    //$("#StudentName").removeAttr("placeholder");
                    // $("#buscarCliente").val(data.data);
                    $('#ClienteDetalle').html(data);
                },
                error: function () {
                    console.log("Error al retornar");
                    // alert("Error while inserting data");
                }
            });
            return false;

        });

        $("#btnSearchProducto").click(function () {

            console.log("dentro de function prodcuto");

            $.ajax({
                type: "POST",
                url: '@Url.Action("BuscarProducto")',
                data: '{keyword: ' + JSON.stringify($("#buscarProducto").val()) + '}',
                dataType: "html",
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // alert("Data has been added successfully.");

                    //$("#StudentName").removeAttr("placeholder");
                    // $("#buscarCliente").val(data.data);
                    $('#ProductoDetalle').html(data);
                },
                error: function () {
                    console.log("Error al retornar");
                    // alert("Error while inserting data");
                }
            });
            return false;

        });


        $("#btnAgregarProducto").click(function () {

            console.log("dentro de function cliente: " + $("#ProductoID").val());


            var flag = 0;

            for (var i = 0; i < productosArray.length; i++) {
                if( productosArray[i].productoID == $("#ProductoID").val())
                {
                    productosArray[i].cantidad += parseInt($("#txtCantidad").val());
                    productosArray[i].subtotal = parseFloat(productosArray[i].cantidad * parseFloat($("#txtPrecio").val()));
                    flag = 1;
                }

            }
            console.log("Antes " + productosArray);

            if (flag == 0) {
                productosArray.push({
                    productoID: $("#ProductoID").val(),
                    descripcion: $("#txtDescripcion").val(),
                    cantidad: parseInt($("#txtCantidad").val()),
                    precio: parseFloat($("#txtPrecio").val()),
                    subtotal: parseFloat(parseInt($("#txtCantidad").val()) *  parseFloat($("#txtPrecio").val()))
                });

            }

            console.log("Despues " + productosArray);
            //var product = { productoID: $("#ProductoID").val(), cantidad: $("#txtCantidad").val() };

            // arrayProductos.push(product);

            //var keyword = JSON.stringify(arrayProductos);
            //var dat = JSON.stringify(arrayProductos);

            // console.log(JSON.stringify($("#buscarProducto").val()));
            console.log(JSON.stringify(productosArray));
            $.ajax({
                type: "POST",
                url: '@Url.Action("AgregarProductoGrid")',
                data: JSON.stringify(productosArray),
                contentType: "application/json; charset=utf-8",
                success: function (data) {
                    // alert("Data has been added successfully.");
                    $('#GridProducto').html(data);
                    CalcularTotal();
                    //$("#StudentName").removeAttr("placeholder");
                    // $("#buscarCliente").val(data.data);
                    console.log("Respuesta:" + data);
                },
                error: function () {
                    console.log("Error al retornar");
                    // alert("Error while inserting data");
                }
            });
            return false;




        });




    });


    </script>
}


<h2>Detalle del Pedido N° : @Html.DisplayFor( x => x.PedidoClienteID )</h2>


<div id="Asignatario">

 @{
     
     SelectList sl = ViewBag.Usuarios;
     @Html.DropDownListFor(m => m.AspNetUsers.UserName, sl, new { @id = "AsignatarioID" })
     
 }

</div>

<br />

<div>

    @Html.Label("Nombre:")
    @Html.TextBox("buscarCliente")

    <button id="btnSearchCliente">Buscar</button>

    <br />
</div>

@using (Html.BeginForm("GuardarCambios", "PedidoCliente", FormMethod.Post))
{



    @Html.AntiForgeryToken()
    @Html.Hidden("hddCliente");
    @Html.Hidden("hddProductos");
    @Html.Hidden("hddTotal");
    @Html.Hidden("hddAsignatario");
    @Html.Hidden("hddPedidoID");





    <div id="ClienteDetalle">

        @Html.Partial("_PartialDetalleCliente", Model.CLIENTES)

    </div>
    <br />
    <div>

        @Html.Label("Buscar Producto:")
        @Html.TextBox("buscarProducto")

        <button id="btnSearchProducto">Buscar</button>

        <br />

    </div>

    <div id="ProductoDetalle">


        @Html.Partial("_PartialDetalleProducto", new WebApplication3.Models.PRODUCTOS())


    </div>
    <br />


    <div>

        @Html.Label("Agregar Producto")

        <button id="btnAgregarProducto">Agregar</button>

        <br />

    </div>

    <div id="GridProducto">

        @{
            List<WebApplication3.Models.ProductosJqueryViewModel> _lst = new List<WebApplication3.Models.ProductosJqueryViewModel>();
            if (ViewBag.Productos != null)
            {
                _lst = ViewBag.Productos;
            }
            
       }


        @Html.Partial("_PartialGridProductos", _lst)


    </div>

    <div>

        <h3>Total : </h3> <input id="txtTotales" disabled="disabled" />

    </div>
    <br />

    <button id="btnsave" onclick="EnviarFormulario()" type="button" class="btn btn-default"> Guardar </button>
}

@Html.ActionLink("Ir a Inicio", "Index")