MVC/WebApplication3/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class PedidoController : Controller
    {
        //
        // GET: /Pedido/
        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Pedido/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //
       
        public ActionResult Create(int tipo)
        {
            if (tipo == 1)
                return RedirectToAction("CrearNuevoPedido", "PedidoCliente");
            else if (tipo == 2)
                return RedirectToAction("CrearNuevoPedido", "PedidoProveedor");
            else
                return RedirectToAction("Index");
        }

        //
        // POST: /Pedido/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Pedido/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Pedido/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Pedido/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Pedido/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC/WebApplication3/Views/Pedido/Index.cshtml
@{
    ViewBag.Title = "Crear Nuevo Pedido";
}

<h2>Index</h2>

<div>
<h2>CREAR NUEVO PEDIDO</h2>
    @using (Html.BeginForm("Create", "Pedido" , FormMethod.Get))
    {
        @Html.AntiForgeryToken()

        <label for="tipo">Nuevo tipo de Pedido:</label>
        <select id="tipo" name="tipo">
            <option value="1">Cliente</option>
            <option value="2">Proveedor</option>
        </select>

        <input type="submit" value="Seleccionar" class="btn btn-default" />

    }

</div>

<div>
    @Html.ActionLink("Back to List", "Index","Home")
</div>