MVC/WebApplication3/Controllers/CuentaClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class CuentaClienteController : Controller
    {
        private CREntities1 db = new CREntities1();

       

        // GET: CuentaCliente
        public ActionResult Index()
        {
            var cUENTAS_CLIENTES = db.CUENTAS_CLIENTES.Include(c => c.CLIENTES);
            return View(cUENTAS_CLIENTES.ToList());
        }

        // GET: CuentaCliente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUENTAS_CLIENTES cUENTAS_CLIENTES = db.CUENTAS_CLIENTES.Find(id);
            if (cUENTAS_CLIENTES == null)
            {
                return HttpNotFound();
            }
            return View(cUENTAS_CLIENTES);
        }

        // GET: CuentaCliente/Create
        public ActionResult Create()
        {
            ViewBag.ClienteID = new SelectList(db.CLIENTES, "ClienteID", "Nombre");
            return View();
        }

        // POST: CuentaCliente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CCuentaID,ClienteID,NumeroCuenta,Descripcion")] CUENTAS_CLIENTES cUENTAS_CLIENTES)
        {
            if (ModelState.IsValid)
            {
                db.CUENTAS_CLIENTES.Add(cUENTAS_CLIENTES);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ClienteID = new SelectList(db.CLIENTES, "ClienteID", "Nombre", cUENTAS_CLIENTES.ClienteID);
            return View(cUENTAS_CLIENTES);
        }

        // GET: CuentaCliente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUENTAS_CLIENTES cUENTAS_CLIENTES = db.CUENTAS_CLIENTES.Find(id);
            if (cUENTAS_CLIENTES == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteID = new SelectList(db.CLIENTES, "ClienteID", "Nombre", cUENTAS_CLIENTES.ClienteID);
            return View(cUENTAS_CLIENTES);
        }

        // POST: CuentaCliente/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CCuentaID,ClienteID,NumeroCuenta,Descripcion")] CUENTAS_CLIENTES cUENTAS_CLIENTES)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cUENTAS_CLIENTES).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ClienteID = new SelectList(db.CLIENTES, "ClienteID", "Nombre", cUENTAS_CLIENTES.ClienteID);
            return View(cUENTAS_CLIENTES);
        }

        // GET: CuentaCliente/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CUENTAS_CLIENTES cUENTAS_CLIENTES = db.CUENTAS_CLIENTES.Find(id);
            if (cUENTAS_CLIENTES == null)
            {
                return HttpNotFound();
            }
            return View(cUENTAS_CLIENTES);
        }

        // POST: CuentaCliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CUENTAS_CLIENTES cUENTAS_CLIENTES = db.CUENTAS_CLIENTES.Find(id);
            db.CUENTAS_CLIENTES.Remove(cUENTAS_CLIENTES);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public PartialViewResult BuscarCuentas(string keyword)
        {
            List<CUENTAS_CLIENTES> cuentas = new List<CUENTAS_CLIENTES>();
            ModelViewMovimientoCuentaCliente cuentaCliente = new ModelViewMovimientoCuentaCliente(1);
            try
            {
                int id = Convert.ToInt32(keyword);
                cuentas = db.CUENTAS_CLIENTES.Where(x => x.ClienteID == id).ToList();

                if (cuentas != null)
                {

                   
                    cuentaCliente.cuentas = new SelectList(cuentas, "CCuentaID", "Descripcion");
                    cuentaCliente.fechaPago = DateTime.Now;

                }


            }
            catch (Exception)
            {
                
                throw;
            }

            return PartialView("_PartialViewDetalleMovimiento", cuentaCliente);
        }

        public string BuscarPedido(string keyword)
        {
            int id = Convert.ToInt32(keyword);

            PEDIDOS_CLIENTES pedido = db.PEDIDOS_CLIENTES.Find(id);

            if (pedido != null)
                return pedido.PedidoClienteID.ToString();
            else
                return "No existen resultados";
        }

        public ActionResult CrearNuevoMovimiento()
        {

            ModelViewMovimientoCuentaCliente mc = new ModelViewMovimientoCuentaCliente(1);

            mc.cliente = new CLIENTES();

            mc.cuentas = new SelectList(String.Empty);

            mc.fechaPago = DateTime.Now;

            mc.fyp = new ModelViewFacturacionYPago();

            mc.fyp.tiposFacturacion = new SelectList(db.TIPO_FACTURACIONES, "TFacturacionID", "Descripcion");

            mc.fyp.tiposPago = new SelectList(db.TIPO_PAGOS, "TPagoID", "Descripcion");

            return View("MovimientoCuentaCliente", mc);
        }

        public ActionResult NuevoMovimiento(FormCollection col)
        {
            //Datos cliente
            var cliente = Request.Form["hddClienteID"];

            //Tipo Pago 
            var contado = Convert.ToBoolean(Request.Form["chk1"].Split(',')[0]);
            var cheque = Convert.ToBoolean(Request.Form["chk2"].Split(',')[0]);
            var mercaderia = Convert.ToBoolean(Request.Form["chk3"].Split(',')[0]);

            var numeroCheque = Request.Form["txtNumeroCheque"];
            var importe =  Convert.ToDecimal(Request.Form["txtImporte"]);
            var detalleMercaderia = Request.Form["areaMercaderia"];
            var valorMercaderia = Convert.ToDecimal(Request.Form["txtValorMercaderia"]);
            var nombreUsuario = Request.Form["txtNombreUsuario"];
            var numeroCuenta = Request.Form["txtNumeroCuenta"];
            // CC o CA
            var cc = Convert.ToBoolean(Request.Form["chkCC"].Split(',')[0]);
            var ca = Convert.ToBoolean(Request.Form["chkCA"].Split(',')[0]);
            
           // var ca = Request.Form["chkCA"];
            
            //Fecha Pago
            var fechaPago = Convert.ToDateTime(Request.Form["fechaPago"]);
            var tipoPago = db.TIPO_PAGOS.Find(Convert.ToInt32(Request.Form["Tipo"]));
            var cuentaCliente = new CUENTAS_CLIENTES();
            if(Request.Form["Cuenta"] == null)
                cuentaCliente = db.CUENTAS_CLIENTES.Find(cliente);
            cuentaCliente = db.CUENTAS_CLIENTES.Find(Convert.ToInt32(Request.Form["Cuenta"]));
            
            //Referencia
            var idReferencia = Request.Form["PedidoID"];
            var detalle = Request.Form["Detalle"];



            ModelViewMovimientoCuentaCliente mc = new ModelViewMovimientoCuentaCliente(1);

            mc.cliente = new CLIENTES();

            mc.cuentas = new SelectList(String.Empty);

            mc.fechaPago = DateTime.Now;

            mc.fyp = new ModelViewFacturacionYPago();

            mc.fyp.tiposFacturacion = new SelectList(db.TIPO_FACTURACIONES, "TFacturacionID", "Descripcion");

            mc.fyp.tiposPago = new SelectList(db.TIPO_PAGOS, "TPagoID", "Descripcion");

            return View("MovimientoCuentaCliente", mc);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MVC/WebApplication3/Views/CuentaCliente/Create.cshtml
@model WebApplication3.Models.CUENTAS_CLIENTES

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CUENTAS_CLIENTES</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group">
            @Html.LabelFor(model => model.ClienteID, "ClienteID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteID", String.Empty)
                @Html.ValidationMessageFor(model => model.ClienteID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroCuenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroCuenta)
                @Html.ValidationMessageFor(model => model.NumeroCuenta)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion)
                @Html.ValidationMessageFor(model => model.Descripcion)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/WebApplication3/Views/CuentaCliente/Delete.cshtml
@model WebApplication3.Models.CUENTAS_CLIENTES

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CUENTAS_CLIENTES</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLIENTES.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLIENTES.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MVC/WebApplication3/Views/CuentaCliente/Details.cshtml
@model WebApplication3.Models.CUENTAS_CLIENTES

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CUENTAS_CLIENTES</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumeroCuenta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CLIENTES.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CLIENTES.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CCuentaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MVC/WebApplication3/Views/CuentaCliente/Edit.cshtml
@model WebApplication3.Models.CUENTAS_CLIENTES

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CUENTAS_CLIENTES</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.CCuentaID)

        <div class="form-group">
            @Html.LabelFor(model => model.ClienteID, "ClienteID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClienteID", String.Empty)
                @Html.ValidationMessageFor(model => model.ClienteID)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumeroCuenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumeroCuenta)
                @Html.ValidationMessageFor(model => model.NumeroCuenta)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion)
                @Html.ValidationMessageFor(model => model.Descripcion)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/WebApplication3/Views/CuentaCliente/Index.cshtml
@model IEnumerable<WebApplication3.Models.CUENTAS_CLIENTES>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NumeroCuenta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CLIENTES.Nombre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NumeroCuenta)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CLIENTES.Nombre)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CCuentaID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CCuentaID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CCuentaID })
        </td>
    </tr>
}

</table>

MVC/WebApplication3/Views/CuentaCliente/MovimientoCuentaCliente.cshtml
@model WebApplication3.Models.ModelViewMovimientoCuentaCliente
@{
    ViewBag.Title = "MovimientoCuentaCliente";
}

@section Scripts
{

    <style>

        .areaDetails {
        
            width:100%;
            margin-top:5%;
        
        }


    </style>

    <script type="text/javascript">

        var productosArray = [];

       
        function BuscarPedido() {

            var id = $("#PedidoID").val();

            console.log(id);

            if (id != 0 && id != undefined) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("BuscarPedido")',
                    data: '{keyword: ' + JSON.stringify(id) + '}',
                    dataType: "html",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        // alert("Data has been added successfully.");
                        if (isNaN(data))
                        {
                            $("#PedidoID").tooltip({
                                animated: 'fade',
                                placement: 'bottom',
                                html: true
                            });

                            $("#PedidoID").attr("data-original-title", data);

                            $("#PedidoID").tooltip('show');
                            $("#PedidoID").val("");
                        }
                        else
                        {
                            $("#PedidoID").val(data);
                            $("#PedidoID").tooltip({
                                animated: 'fade',
                                placement: 'bottom',
                                html: true
                            });

                            $("#PedidoID").attr("data-original-title", "Pedido Encontrado N° :" + data);

                            $("#PedidoID").tooltip('show');
                        }
                       // console.log("Resultado " + data);
                        //$("#StudentName").removeAttr("placeholder");
                        // $("#buscarCliente").val(data.data);
                        //$('#detalleMovimiento').html(data);
                    },
                    error: function () {
                        console.log("Error al retornar");
                        // alert("Error while inserting data");
                    }
                });
            }
            return false;


        }



        function CalcularTotal() {



            var a = $('.subtotal').not('.grid-header');
            console.log("valor de a :" + a[0].innerText);
            var total = parseFloat(0);

            for (var i = 0; i < a.length; i++) {

                console.log(parseFloat(a[i].innerText.replace("$", "")))
                total += parseFloat(a[i].innerText.replace("$", ""));

            }
            console.log("valor de total: " + total);
            $('#txtTotales').val(total);

        }


        function EnviarFormulario () {



            $('#hddCliente').val($('#hddClienteID').val());
            $('#hddProductos').val(JSON.stringify(productosArray));
            $('#hddTotal').val($('#txtTotales').val());
            $('#hddAsignatario').val($('#Usuarios').val());
           // $('#hddTipoPago').val($('#slTipoPagos').val());
            $('#hddTipoFacturacion').val($('#TipoFacturacion').val());

            console.log($('#hddCliente').val());
            console.log($('#hddAsignatario').val());
            console.log($('#hddProductos').val());
            console.log($('#hddTotal').val());
            console.log($('#hddTipoPago').val());
            console.log($('#hddTipoFacturacion').val());

            $('form')[0].submit();

        }

        function chkNumeroPedido() {

            var chk = $("#numeroPedido");
           
            if (chk.prop("checked")) {
                $("#PedidoID").removeAttr("disabled");
                $("#btnBuscarPedido").removeAttr("disabled");
            }
            if (!chk.prop("checked")) {
                $("#PedidoID").attr("disabled", "disabled");
                $("#btnBuscarPedido").attr("disabled", "disabled");
            }

        }

        function cambiarTextArea() {

            var chk = $('#chkTextArea');
            
            if (chk.prop("checked")) {
                    $("#Detalle").removeAttr("disabled");
           
                }
            if (!chk.prop("checked")) {
                    $("#Detalle").attr("disabled", "disabled");
           
                }
            

        }


        $(function () {

            

          
           
            $("#btnSearchCliente").click(function () {

                console.log("dentro de function cliente");
                //console.log('{keyword: ' + JSON.stringify($("#buscarCliente").val()) + '}');
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("BuscarNombreCliente","PedidoCliente")',
                    data: '{keyword: ' + JSON.stringify($("#buscarCliente").val()) + '}',
                    dataType: "html",
                    contentType: "application/json; charset=utf-8",
                    success: function (data) {
                        // alert("Data has been added successfully.");
                        //var id = data.find("#hddClienteID");
                        var id = $(data).find("#hddClienteID").val();
                        //console.log("Cliente dentro del Return: " + $(data).find("#hddClienteID"));
                        //console.log("Cliente dentro del Return: " + data);
                        //$("#StudentName").removeAttr("placeholder");
                        // $("#buscarCliente").val(data.data);
                        $('#ClienteDetalle').html(data);
                        BuscarCuentas(id);
                    },
                    error: function () {
                        console.log("Error al retornar");
                        // alert("Error while inserting data");
                    }
                });

               // BuscarCuentas();
                return false;

            });

            function BuscarCuentas(id) {

                //var id = $("#hddClienteID").val();

              
                if (id != 0 && id != undefined) {
                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("BuscarCuentas")',
                        data: '{keyword: ' + JSON.stringify(id) + '}',
                        dataType: "html",
                        contentType: "application/json; charset=utf-8",
                        success: function (data) {
                            // alert("Data has been added successfully.");
                           
                            //$("#StudentName").removeAttr("placeholder");
                            // $("#buscarCliente").val(data.data);
                            $('#detalleMovimiento').html(data);
                        },
                        error: function () {
                            console.log("Error al retornar");
                            // alert("Error while inserting data");
                        }
                    });
                }
                return false;


            }


        });


    </script>
}

<h2>Ingrese Detalle de Cuenta para Cliente</h2>

<br />  

@using (Html.BeginForm("NuevoMovimiento", "CuentaCliente"))
{
    @Html.AntiForgeryToken()

    <div>

        @Html.Label("Nombre:")
        @Html.TextBox("buscarCliente")

        <button id="btnSearchCliente">Buscar</button>

        <br />
    </div>

    <div id="ClienteDetalle">

        @Html.Partial("_PartialDetalleCliente", Model.cliente)

    </div>

    <div id="facturacionypago" class="row">

        @Html.Partial("_PartialFacturacionYPago", Model.fyp)

    </div>

    <div id="detalleMovimiento" class="row">

        @Html.Partial("_PartialViewDetalleMovimiento", Model)

    </div>
       
    
    <input type="submit" value="Generar" />
    
}

<br />

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MVC/WebApplication3/Views/CuentaCliente/_PartialViewDetalleMovimiento.cshtml
@model WebApplication3.Models.ModelViewMovimientoCuentaCliente

<h3>Detalle del Movimiento</h3>

<div class="col-lg-12">
    <div class="row">
        <h2>Pago</h2>
        <div class="col-lg-3">
            @Html.Label("Fecha de Pago:", new { For = "fechaPago" })
            @Html.TextBoxFor(model => model.fechaPago, new { @class = "datepicker", @type = "date" })


        </div>

        <div class="col-lg-3">
            @Html.Label("Tipo:", new { For = "Tipo" })
            @Html.DropDownList("Tipo", @Model.tipo)

        </div>

        <div id="SeccionCuenta" class="col-lg-3">
            @Html.Label("Cuenta:")
            @Html.DropDownList("Cuenta", @Model.cuentas)
        </div>
    </div>
    <div class="row">
        <h2>Referencia</h2>
        <div class="col-lg-12">
            <div class="row">
                <div class="col-md-12"> @Html.CheckBox("numeroPedido", false, new { onchange = "chkNumeroPedido();" }) @Html.Label("Referencia a Pedido :") @Html.TextBox("PedidoID", String.Empty , new { disabled = "disabled" }) <button type="button" id="btnBuscarPedido" disabled="disabled" onclick="BuscarPedido();"> Buscar </button></div>
            </div>
            <div class="row">
                <div class="col-md-3">
                   

                </div>
            </div>
            <div class="row">
                <div class="col-md-3">@Html.CheckBox("chkTextArea", false, new { onchange = "cambiarTextArea();" }) @Html.Label("Detalles:", new { For = "Detalle" }) @Html.TextArea("Detalle", Model.detalle, new { Class = "areaDetails", disabled = "disabled" }) </div>
            </div>
            
        </div>
    </div>
</div>